### ISSUE TITLE
PC适配问题

### ISSUE THREAD

**Issue by owen800q** [zpfnb/desktop-music#1]
界面简洁挺不错的，不过，如果宽和高能适配viewport就好了，不然用chrome 把网页保存到电脑桌面PWA应用时，使用体验比较差。
想这里白色空出来的一大块区域..
![image](https://user-images.githubusercontent.com/19252045/83002577-cf541780-a03f-11ea-9990-64a1d14cbf10.png)

**Comment by zpfnb** [comment]
谢谢了，做的时候没太想适配，先把功能搞出来再搞兼容
