### ISSUE TITLE
焦点会跳动 

### ISSUE THREAD

**Issue by amusez** [zpfnb/desktop-music#3]
1.发送弹幕的时候 弹幕内容会被双引号包起来
2.在弹幕输入框中使用qq拼音输入法在中文状态下输入ws,输入焦点会自动跳到搜索框

**Comment by zpfnb** [comment]
谢谢提问题了。但我解释下：
1.为了区分弹幕，我故意给自己发送的弹幕加了双引号
2.可以看下README，s（search）是搜索的快捷键，按下s就会自动聚焦的

**Comment by zpfnb** [comment]
已修复（发送弹幕框输入s键，顶部搜索框自动对焦）
